/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configuracoes` | `/configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/despesa` | `/despesa`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/metas` | `/metas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/movimentacoes` | `/movimentacoes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/receita` | `/receita`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/configuracoes` | `/configuracoes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/despesa` | `/despesa`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/metas` | `/metas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/movimentacoes` | `/movimentacoes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/receita` | `/receita`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/configuracoes${`?${string}` | `#${string}` | ''}` | `/configuracoes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/despesa${`?${string}` | `#${string}` | ''}` | `/despesa${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/metas${`?${string}` | `#${string}` | ''}` | `/metas${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/movimentacoes${`?${string}` | `#${string}` | ''}` | `/movimentacoes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/receita${`?${string}` | `#${string}` | ''}` | `/receita${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configuracoes` | `/configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/despesa` | `/despesa`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/metas` | `/metas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/movimentacoes` | `/movimentacoes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/receita` | `/receita`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
