/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `/despesa`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/metas`; params?: Router.UnknownInputParams; } | { pathname: `/movimentacoes`; params?: Router.UnknownInputParams; } | { pathname: `/receita`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/config/gerenciar-categorias`; params?: Router.UnknownInputParams; } | { pathname: `/config/gerenciar-contas`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/configuracoes`; params?: Router.UnknownOutputParams; } | { pathname: `/despesa`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/metas`; params?: Router.UnknownOutputParams; } | { pathname: `/movimentacoes`; params?: Router.UnknownOutputParams; } | { pathname: `/receita`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/config/gerenciar-categorias`; params?: Router.UnknownOutputParams; } | { pathname: `/config/gerenciar-contas`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/configuracoes${`?${string}` | `#${string}` | ''}` | `/despesa${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/metas${`?${string}` | `#${string}` | ''}` | `/movimentacoes${`?${string}` | `#${string}` | ''}` | `/receita${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/config/gerenciar-categorias${`?${string}` | `#${string}` | ''}` | `/config/gerenciar-contas${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `/despesa`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/metas`; params?: Router.UnknownInputParams; } | { pathname: `/movimentacoes`; params?: Router.UnknownInputParams; } | { pathname: `/receita`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/config/gerenciar-categorias`; params?: Router.UnknownInputParams; } | { pathname: `/config/gerenciar-contas`; params?: Router.UnknownInputParams; };
    }
  }
}
